[package]
name = "subtitle-fast-comparator"
version = "0.1.0"
edition = "2024"

[dependencies]
subtitle-fast-types = { path = "../subtitle-fast-types" }
rayon = "1.10"

[dev-dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
indicatif = "0.17"
